In [22]:
import pandas as pd
import pyarrow.feather as feather
import geopandas as gpd

In [23]:
# Replace 'your_file_path.feather' with the path to your .feather file
df = feather.read_feather('./OneDrive_1_2-8-2024/SMM_HRUs_SCA.feather')

In [24]:
# Set the 'datetime' column as the index
df.set_index('datetime', inplace=True)

In [25]:
# Remove 'nhmHRU' prefix and convert the remaining part to an integer for each column name
df.columns = [int(col.replace('nhmHRU', '')) for col in df.columns]

In [27]:
gdf = gpd.read_file('./HYPE_Geospacial/HYPE_validated_shapefile.shp')

In [28]:
# Create a mapping dictionary from 'hru_nhm' to 'seg_nhm'
mapping_dict = dict(zip(gdf['hru_nhm'], gdf['seg_nhm']))

In [30]:
# Rename columns in the DataFrame using the mapping dictionary
df.rename(columns=mapping_dict, inplace=True)

In [32]:
# Convert row index to datetime
df.index = pd.to_datetime(df.index)

# Trim anything later than 2015-12-31
df = df[df.index <= '2015-12-31']

In [33]:
df

,58219,58241,58237,58232,58214,58233,58213,58223,58221,58216,...,58448,58380,58342,58582,58405,58610,58389,58570,58579,58465
datetime,,,,,,,,,,,,,,,,,,,,,
2002-07-04,0.069929,0.000000,0.000000,0.000000,0.014059,0.000000,0.0,0.008473,0.000000,0.049473,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00000
2002-07-05,0.278127,0.359946,0.608275,0.444227,0.035810,0.364286,0.0,0.153291,0.109535,0.265214,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00000
2002-07-06,0.163252,0.446060,0.710294,0.092380,0.018791,0.329780,0.0,0.140699,0.000000,0.172948,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00000
2002-07-07,0.400748,0.596167,0.978750,0.337101,0.067345,0.459770,0.0,0.317924,0.157710,0.382561,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00000
2002-07-08,0.397154,0.596167,0.978750,0.337101,0.078228,0.434187,0.0,0.317924,0.157710,0.382561,...,0.009555,0.0,0.0,0.0,0.002148,0.0,0.0,0.020941,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-27,0.916190,0.905095,1.000000,1.000000,0.961443,0.953759,1.0,0.966056,0.999920,0.979500,...,0.867982,1.0,1.0,1.0,0.994287,1.0,1.0,1.000000,1.0,1.00000
2015-12-28,0.916826,0.905095,1.000000,1.000000,0.961443,0.953759,1.0,0.966056,0.999920,0.979500,...,0.867982,1.0,1.0,1.0,0.994287,1.0,1.0,1.000000,1.0,1.00000
2015-12-29,0.916826,0.905095,1.000000,1.000000,0.961443,0.953759,1.0,0.966056,0.999920,0.979500,...,0.867982,1.0,1.0,1.0,0.994287,1.0,1.0,1.000000,1.0,1.00000
2015-12-30,0.918100,0.905095,1.000000,1.000000,0.961558,0.969060,1.0,0.962631,0.999920,0.987769,...,0.867982,1.0,1.0,1.0,0.994287,1.0,1.0,1.000000,1.0,1.00000
2015-12-31,0.918100,0.905095,1.000000,1.000000,0.961558,0.969060,1.0,0.962631,0.999920,0.987769,...,0.867982,1.0,1.0,1.0,0.994287,1.0,1.0,1.000000,1.0,0.99935

In [34]:
# Save DataFrame to a space-separated text file
df.to_csv('./HYPE_SCA', sep=' ')